baseURL = "http://LiyAy87.github.io/distancia"
languageCode = "en-us"
title = "My New Hugo Site"
theme= "learn"
#Idioma por defecto
defaultContentLanguage="es"
#Color Stilo
[params]
  themeVariant = "dwes"

  [Languages]
    [Languages.es]
        title = "Ejemplo para el uso de idiomas"
        weight = 1
        languageName = "Español"
        landingPageURL = "http://cpilosenlaces.com"
        landingPageName = "<i class='fas fa-laptop-code'></i> Distancia-DWES"
        ContentDir= "content/es"
    [Languages.en]
        title = "Example use language"
        weight = 2
        languageName = "English"
        landingPageURL = "http://cpilosenlaces.com"
        landingPageName = "<i class='fas fa-laptop-code'></i> Distancia-DWES"
        ContentDir= "content/en"
    [Languages.fr]
        title = "Exemple d'utilisation des langues"
        weight = 3
        languageName = "Français"
        landingPageURL = "http://cpilosenlaces.com"
        landingPageName = "<i class='fas fa-laptop-code'></i> Distancia-DWES"
        ContentDir="content/fr"


[[menu.shortcuts]]
name="<i class='fab fa-hire-a-helper'></i> Hugo"
identified=""
url="https://gohugo.io"
weight=1

[[menu.shortcuts]]
name="<i class='fas fa-mouse-pointer'></i> Dwes Infenlaces"
identified=""
url="http://dwes.infenlaces.com/hugo/staticSite/public/index.html"
weight=2

[[menu.shortcuts]]
name="<i class='fab fa-wikipedia-w'></i>   Wiki del curso"
identified=""
url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
weight=3

[[menu.shortcuts]]
name="<i class='far fa-question-circle'></i>   Ejercicios resueltos"
identified=""
url="http://manuel.infenlaces.com/dwes/ejercicios/"
weight=4
